version: '3.8'

services:
  vendas-sql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: vendas-sql-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=!Senhafacil1234
    ports:
      - "1433:1433"

  vendas-rabbitmq:
    image: rabbitmq:3-management 
    container_name: vendas-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"   
      - "15672:15672"